apiBaseUrl=http://localhost:4111
apiVersion=/api/v1

admin.username=admin
admin.password=admin

uiRemote=http://localhost:4444/wd/hub
uIBaseUrl=http://172.28.64.1:3000
browser=chrome
browserSize=1920x1080

# Database configuration
db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver
db.table.customers=customers

# Fraud service configuration (for testing with WireMock)
fraud.service.url=http://localhost:8080