apiBaseUrl=http://localhost:4111
apiVersion=/api/v1/

admin.username=admin
admin.password=admin

uIremote=http://localhost:4444/wd/hub
uIBaseUrl=http://172.28.64.1:3000
browser=chrome
browserSize=1920x1080