### Get auth token
### Admin Token: Authorization: Basic YWRtaW46YWRtaW4=
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Get auth token for "username": "kate19981"
### Authorization: Basic a2F0ZTE5OTgxOnZlcnlzVFJvbmdQYXNzd29yZDMzJDE=
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "kate19981",
  "password": "verysTRongPassword33$1"
}

### Positive test: Admin can create new user with correct data
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate19981",
  "password": "verysTRongPassword33$1",
  "role": "USER"
}

### Negative test: Admin cannot create new user with blanck username
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "",
  "password": "verysTRongPassword33$2",
  "role": "USER"
}

### Negative test: Admin cannot create new user with username 2 or 16 characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "ab",
  "password": "verysTRongPassword33$3",
  "role": "USER"
}

### Negative test: Admin cannot create new user with username 2 or 16 characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "abchdyksnrpagemk",
  "password": "verysTRongPassword33$4",
  "role": "USER"
}

### Negative test: Admin cannot create new user with username contains $%^&*()@# characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "$%^&*()@#",
  "password": "verysTRongPassword33$4",
  "role": "USER"
}

### Negative test: Admin cannot create new user with blank password
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate19982",
  "password": "",
  "role": "USER"
}

### Negative test: Admin cannot create new user with password less then 8 characters
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate19983",
  "password": "1234567",
  "role": "USER"
}

### Negative test: Admin cannot create new user without password without digits
### Negative test: Admin cannot create new user without password without one lower case character
### Negative test: Admin cannot create new user without password without one uppercase
### Negative test: Admin cannot create new user without password without special character
### Negative test: Admin cannot create new user without password with spaces
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate19984",
  "password": "?",
  "role": "USER"
}

### Negative test: Admin cannot create new user with role not from list: "ADMIN", "USER"
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate19985",
  "password": "verysTRongPassword33$5",
  "role": "EDITOR"
}

### Positive test: Authorized user can create account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOnZlcnlzVFJvbmdQYXNzd29yZDMzJDE=

### Positive test: Check account was created
GET http://localhost:4111/api/v1/customer/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOnZlcnlzVFJvbmdQYXNzd29yZDMzJDE=

### Negative test: Create user that already exists by admin
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate1998",
  "password": "verysTRongPassword33$",
  "role": "USER"
}